spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev #开发环境
  aplication:
   name: microservicecloud-config-lintao-dev
---
spring:
 profiles: test #开发环境
 aplication:
  name: microservicecloud-config-lintao-test
---
#utf-8保存
